[package]
name = "egor00f/instance-types-as-tables"

description = "This library contain the typ exports of roblox types(with docs). It can be used for creating types that mimicking for roblox types"

version = "0.1.1"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github/"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]
